apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tuplestream

secretGenerator:
  - name: collector-auth-token
    literals:
    - token=TODO

resources:
  - namespace.yaml
  - collector.yaml
