apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawkeye-sidecar
spec:
  selector:
    matchLabels:
      app: hawkeye-sidecar
  template:
    metadata:
      labels:
        app: hawkeye-sidecar
    spec:
      containers:
      - name: hawkeye-sidecar
        image: sc-local:SOMEVERSION
        env:
          - name: HAWKEYE_TARGET
            value: http://host.docker.internal:8080
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 32Mi
        livenessProbe:
          httpGet:
            path: /ping
            port: 8889
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
spec:
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - name: loadgen
        image: loadgen:foo
