version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build . -t m0wfo/hawkeye-sidecar:latest
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push m0wfo/hawkeye-sidecar:latest
